-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgd/Bs7LAZC+jznm//
XjnQemm7bCTKsn7hnMYhcMLL0tmgCgYIKoZIzj0DAQehRANCAASrLkxVQpyuhEKH
Q50At9TvPXSXapC+TL9THDqqgvgxrI1M8q+53eYECcjR/JsCVLYtV1u3SfiAea91
N0KcTY00
-----END PRIVATE KEY-----